// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMZQ838nlPCunef2j9ACH6pscbd2IPswA',
    appId: '1:827641304531:web:bc9a05ba33d7a31ee24b26',
    messagingSenderId: '827641304531',
    projectId: 'tablet-comparison-app',
    authDomain: 'tablet-comparison-app.firebaseapp.com',
    storageBucket: 'tablet-comparison-app.appspot.com',
    measurementId: 'G-83PFP1WF1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJKBSJ0sS2KB2-7jZkKgtMrhKiFoNfJdw',
    appId: '1:827641304531:android:c6a4095dced236e4e24b26',
    messagingSenderId: '827641304531',
    projectId: 'tablet-comparison-app',
    storageBucket: 'tablet-comparison-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLevMuruFP7tPC02aFKSn-zIvcTK0Uaws',
    appId: '1:827641304531:ios:81d2d6e5f09d2139e24b26',
    messagingSenderId: '827641304531',
    projectId: 'tablet-comparison-app',
    storageBucket: 'tablet-comparison-app.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLevMuruFP7tPC02aFKSn-zIvcTK0Uaws',
    appId: '1:827641304531:ios:2b4e4c81121c2d71e24b26',
    messagingSenderId: '827641304531',
    projectId: 'tablet-comparison-app',
    storageBucket: 'tablet-comparison-app.appspot.com',
    iosBundleId: 'com.example.mobileApp.RunnerTests',
  );
}
